### ISSUE TITLE
Access to data used in the project

### ISSUE THREAD

**Issue by mkbond777** [lvrcek/NeuralLayout#1]
I have landed to this repo after going through the paper at https://arxiv.org/pdf/2011.05013.pdf.

I am trying to understand the code by running it in my local machine but found that dataset used is not provided as 
```
train_path = 'data/train'
test_path = 'data/test'
```
which are relative paths.

By any chance, will you guys be able to provide me access to the data used please?

**Comment by lvrcek** [comment]
Sure thing!
I updated the graph_generator module and you can generate the graphs by running it. You will find that the `store_path` is a positional argument now, and you can specify it to be `data/train` and then in the next run `data/test`. That way you will be able to run the training loop immediately without changing the code. You can also see that there are several different optional arguments (one for each type of graphs) available in the graph_generator, but I recommend that  you use `--training` for generating the training graphs, and `--testing` for testing graphs. That will not generate exactly the same graphs as used in the paper, but will generate the graphs from the same distribution, and the results of training/testing should be quite similar.

Therefore, after updating the project you have cloned, simply run:
```
python graph_generator.py data/train --training
python graph_generator.py data/test --testing
```

**Comment by mkbond777** [comment]
Thanks @lvrcek!
Looks like you guys are using synthetic data generated using the generator methods.

Just curious, did you guys also test your model with some real data ?

**Comment by lvrcek** [comment]
We did! We tested on the assembly graphs of lambda phage and E. coli, which you can find on this link:
https://drive.google.com/file/d/1qDVXhv88IZlrFQt0fFLnDMLyceqH45sw/view?usp=sharing

Here you can find the reads in the FASTQ format, and the graphs in TXT and CSV format. The easiest way to test on the these data is to simply copy the TXT files into the `raw` directory of your dataset. By running `train.py`, PyTorch Geomtric will recognize there isdata in the `raw` directory, but not in the `processed` directory, and will call the methods needed to process the TXT files into PyTorch tensors and save them into `processed`.

Therefore, to achieve this your file system would look something like this:
```
data
   -test
       -raw
           -ecoli.txt
           -lambda.txt
       -processed
```

You can also find original reads from which the graphs were generated, but getting the graphs from the reads is a bit more complicated. It includes using a third-party tool and parsing the intermediate outputs it produces. I will fix the code so that you can try that as well, and will get back to you once I am done.

**Comment by mkbond777** [comment]
Hey @lvrcek ,

This is super helpful. I will try this for sure.

I will also wait for that fix which will let me create graphs from the reads.

By the way from here you downloaded the reads for Lambda phage and E. coli ?

Thanks
Manish

**Comment by lvrcek** [comment]
The lambda phage reads were downloaded from [Raven's github page](https://github.com/lbcb-sci/raven/blob/master/test/data/ERA476754.fastq.gz). Raven is also the third-party tool I mentioned in the previous comment, which I use for creating the assembly graphs. It is a _de novo_ assembler for Oxford Nanopore and PacBio reads. ANd just to mention, both lambda phage and E. coli reads were sequenced with Oxford Nanopore sequencers.

E. coli reads were downloaded from downloade from [LomanLab](http://lab.loman.net/2015/09/24/first-sqk-map-006-experiment/) as FAST5 and then basecalled by our lab. Therefore, these reads cannot be found elsewhere.

Hope this helps :)

**Comment by mkbond777** [comment]
> Sure thing!
> I updated the graph_generator module and you can generate the graphs by running it. You will find that the `store_path` is a positional argument now, and you can specify it to be `data/train` and then in the next run `data/test`. That way you will be able to run the training loop immediately without changing the code. You can also see that there are several different optional arguments (one for each type of graphs) available in the graph_generator, but I recommend that you use `--training` for generating the training graphs, and `--testing` for testing graphs. That will not generate exactly the same graphs as used in the paper, but will generate the graphs from the same distribution, and the results of training/testing should be quite similar.
> 
> Therefore, after updating the project you have cloned, simply run:
> 
> ```
> python graph_generator.py data/train --training
> python graph_generator.py data/test --testing
> ```

Although above command helped me in generating train and test data, I am getting below error while running:
`python train.py`
Error:
```
algorithm_dataset_base.py", line 16, in len
    return len(os.listdir(self.processed_dir)) - 2
FileNotFoundError: [Errno 2] No such file or directory: 'data/train/processed'
```
I also verified the directory structure generated and it is something like below:
```
data
 -train
      -training_chain_0.txt
       ........
       ........
       -training_chain_99.txt
```
So there is no folder named processed

**Comment by lvrcek** [comment]
Hi @mkbond777, thanks for pointing this out. I updated the code in several ways and this should be fixed now - in case there is no directory processed in either train or test directory, it will be created automatically.

Second, I added the Raven assembler as a submodule, which now allows you create graphs from the FASTQ files.

I suggest you follow the instructions in the README, which is also updated. Note that in order to run Raven there are some dependencies. I have also included two plug&play examples which you should be able to run immediately, as long as you have all the necessary Python packages installed. Soon I will also include the package requirements in order to make the installation even easier.

Let me know if you will have any additional questions.

EDIT: As of know, you can also find the requirements.txt file and instructions how to set up the environment.

**Comment by mkbond777** [comment]
Thank you very much @lvrcek for responding so quickly. I will try again and let you know in case of any issue.
